import { StyleSheet } from 'react-native';
export const lightColors = {
  background: '#F4F6FA',
  surface: '#FFFFFF',
  text: '#172B49',
  textMuted: '#52647C',
  primary: '#2457C5',
  primarySoft: '#EAF0FF',
  border: '#E0E7F0',
  hero: '#172C4F',
  heroSurface: '#253E68',
  onHero: '#FFFFFF',
  heroMuted: '#C1CFE3',
  heroAccent: '#B6CAFF',
  onPrimary: '#FFFFFF',
  success: '#187451',
  successSoft: '#E5F4EB',
  warning: '#86570C',
  warningSoft: '#FFF3DA',
  error: '#B43C4B',
  errorSoft: '#FCECEF',
  disabled: '#E0E6EF',
  onDisabled: '#536176',
  accent: '#087D80',
};
export type ThemeColors = typeof lightColors;
export const darkColors: ThemeColors = {
  background: '#101823',
  surface: '#192535',
  text: '#EDF3FC',
  textMuted: '#B0BFD2',
  primary: '#9BBEFF',
  primarySoft: '#233A5B',
  border: '#3C4E65',
  hero: '#182C48',
  heroSurface: '#284466',
  onHero: '#F3F7FF',
  heroMuted: '#C1CFE3',
  heroAccent: '#B6CAFF',
  onPrimary: '#102443',
  success: '#82D9AE',
  successSoft: '#183D31',
  warning: '#F3CA7B',
  warningSoft: '#40331D',
  error: '#FFADB6',
  errorSoft: '#472933',
  disabled: '#2C394B',
  onDisabled: '#A9B7CA',
  accent: '#6ADAD3',
};
export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    page: { flex: 1, backgroundColor: colors.background },
    content: {
      padding: 22,
      paddingBottom: 40,
      gap: 20,
      width: '100%',
      maxWidth: 680,
      alignSelf: 'center',
    },
    stack: { gap: 12 },
    eyebrow: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.6,
      color: colors.textMuted,
    },
    iconTile: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.primarySoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    spread: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    flex: { flex: 1 },
    title: {
      fontSize: 32,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.8,
    },
    heading: { fontSize: 18, fontWeight: '700', color: colors.text },
    body: { fontSize: 14, lineHeight: 22, color: colors.textMuted },
    small: { fontSize: 12, lineHeight: 18, color: colors.textMuted },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 20,
      gap: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.hero,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 14,
      color: colors.text,
      backgroundColor: colors.background,
      fontSize: 15,
    },
    divider: { height: 1, backgroundColor: colors.border },
    wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  });
