import { StyleSheet } from 'react-native';
export const lightColors = {
  background: '#F2F5F4',
  surface: '#FFFFFF',
  surfaceElevated: '#E8EFEC',
  textPrimary: '#172B49',
  textSecondary: '#52647C',
  danger: '#B43C4B',
  allowed: '#187451',
  review: '#86570C',
  blocked: '#B43C4B',
  text: '#172B49',
  textMuted: '#52647C',
  primary: '#087963',
  primarySoft: '#E1F3EC',
  border: '#D8E3DE',
  hero: '#172C4F',
  heroSurface: '#253E68',
  onHero: '#FFFFFF',
  heroMuted: '#C1CFE3',
  heroAccent: '#B6CAFF',
  onPrimary: '#FFFFFF',
  success: '#187451',
  successSoft: '#E5F4EB',
  warning: '#86570C',
  warningSoft: '#FFF3DA',
  error: '#B43C4B',
  errorSoft: '#FCECEF',
  disabled: '#E0E6EF',
  onDisabled: '#536176',
  accent: '#087D80',
  protected: '#087963',
  inactive: '#52647C',
  inactiveSoft: '#E8EFEC',
  input: '#EDF2EF',
  overlay: '#091511AA',
};
export type ThemeColors = typeof lightColors;
export const darkColors: ThemeColors = {
  background: '#0C1212',
  surface: '#151F1F',
  surfaceElevated: '#1E2D2B',
  textPrimary: '#EDF3FC',
  textSecondary: '#B0BFD2',
  danger: '#FFADB6',
  allowed: '#82D9AE',
  review: '#F3CA7B',
  blocked: '#FFADB6',
  text: '#EDF3FC',
  textMuted: '#B0BFD2',
  primary: '#62E0B9',
  primarySoft: '#173A30',
  border: '#334542',
  hero: '#182C48',
  heroSurface: '#284466',
  onHero: '#F3F7FF',
  heroMuted: '#C1CFE3',
  heroAccent: '#B6CAFF',
  onPrimary: '#08261D',
  success: '#82D9AE',
  successSoft: '#183D31',
  warning: '#F3CA7B',
  warningSoft: '#40331D',
  error: '#FFADB6',
  errorSoft: '#472933',
  disabled: '#2C394B',
  onDisabled: '#A9B7CA',
  accent: '#6ADAD3',
  protected: '#62E0B9',
  inactive: '#B0BFD2',
  inactiveSoft: '#1E2D2B',
  input: '#101A19',
  overlay: '#020807BB',
};
export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  huge: 32,
};
export const radii = { input: 14, card: 24, pill: 100 };
export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    page: { flex: 1, backgroundColor: colors.background },
    content: {
      padding: 20,
      paddingBottom: 40,
      gap: 16,
      width: '100%',
      maxWidth: 680,
      alignSelf: 'center',
    },
    stack: { gap: 12 },
    resultIcon: { alignItems: 'center', paddingVertical: 12 },
    ruleRow: {
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingVertical: 12,
      gap: 12,
    },
    ruleSummary: { minHeight: 52 },
    eyebrow: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.6,
      color: colors.textMuted,
    },
    iconTile: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.primarySoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    spread: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    flex: { flex: 1 },
    title: {
      fontSize: 26,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.8,
    },
    heading: { fontSize: 18, fontWeight: '700', color: colors.text },
    body: { fontSize: 14, lineHeight: 22, color: colors.textMuted },
    small: { fontSize: 12, lineHeight: 18, color: colors.textMuted },
    card: {
      backgroundColor: colors.surface,
      borderRadius: radii.card,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.xl,
      gap: 12,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 14,
      color: colors.text,
      backgroundColor: colors.input,
      fontSize: 15,
    },
    divider: { height: 1, backgroundColor: colors.border },
    wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    modeOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderWidth: 1,
      borderRadius: 16,
      padding: 14,
      minHeight: 80,
    },
    modeDisabled: { opacity: 0.65 },
  });
