import { StyleSheet } from 'react-native';
export const colors = {
  background: '#F4F6FA',
  white: '#FFFFFF',
  ink: '#172B49',
  muted: '#61728A',
  blue: '#315AE8',
  blueSoft: '#EAF0FF',
  border: '#E0E7F0',
  navy: '#172C4F',
  green: '#187451',
  greenSoft: '#E5F4EB',
  amber: '#86570C',
  amberSoft: '#FFF3DA',
  red: '#B43C4B',
  redSoft: '#FCECEF',
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  content: { padding: 22, paddingBottom: 32, gap: 18 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  spread: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  flex: { flex: 1 },
  title: {
    fontSize: 29,
    fontWeight: '700',
    color: colors.ink,
    letterSpacing: -0.8,
  },
  heading: { fontSize: 18, fontWeight: '700', color: colors.ink },
  body: { fontSize: 14, lineHeight: 22, color: colors.muted },
  small: { fontSize: 12, lineHeight: 18, color: colors.muted },
  card: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: colors.ink,
    backgroundColor: colors.background,
    fontSize: 15,
  },
  divider: { height: 1, backgroundColor: colors.border },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
});
